use('company')

// db.getCollectionInfos()

// db.listCollections()
// db.emoployee.deleteMany({})



// db.emoployee.insertMany([{
//     "first_name": "Genevieve",
//     "last_name": "Hanssmann",
//     "email": "ghanssmann0@chron.com",
//     "gender": "Female",
//     "doj": "2020-10-02"
//   }, {
//     "first_name": "Neysa",
//     "last_name": "Catonnet",
//     "email": "ncatonnet1@stanford.edu",
//     "gender": "Female",
//     "doj": "2022-02-05"
//   }, {
//     "first_name": "Robinet",
//     "last_name": "Shemilt",
//     "email": "rshemilt2@prnewswire.com",
//     "gender": "Male",
//     "doj": "2023-05-25"
//   }, {
//     "first_name": "Valentina",
//     "last_name": "Boyen",
//     "email": "vboyen3@feedburner.com",
//     "gender": "Female",
//     "doj": "2022-06-11"
//   }, {
//     "first_name": "Hamid",
//     "last_name": "Sydenham",
//     "email": "hsydenham4@symantec.com",
//     "gender": "Male",
//     "doj": "2020-02-24"
//   }, {
//     "first_name": "Perry",
//     "last_name": "Hanne",
//     "email": "phanne5@blog.com",
//     "gender": "Male",
//     "doj": "2024-03-10"
//   }, {
//     "first_name": "Jennifer",
//     "last_name": "Le Barr",
//     "email": "jlebarr6@shutterfly.com",
//     "gender": "Female",
//     "doj": "2023-09-02"
//   }, {
//     "first_name": "Ashli",
//     "last_name": "Piwell",
//     "email": "apiwell7@nba.com",
//     "gender": "Female",
//     "doj": "2019-12-10"
//   }, {
//     "first_name": "Mohammed",
//     "last_name": "Ismead",
//     "email": "mismead8@census.gov",
//     "gender": "Male",
//     "doj": "2023-02-26"
//   }, {
//     "first_name": "Chiquita",
//     "last_name": "Awmack",
//     "email": "cawmack9@ted.com",
//     "gender": "Female",
//     "doj": "2024-10-08"
//   }, {
//     "first_name": "Deonne",
//     "last_name": "Massenhove",
//     "email": "dmassenhovea@e-recht24.de",
//     "gender": "Female",
//     "doj": "2023-10-29"
//   }, {
//     "first_name": "Brose",
//     "last_name": "Bazylets",
//     "email": "bbazyletsb@abc.net.au",
//     "gender": "Male",
//     "doj": "2024-10-02"
//   }, {
//     "first_name": "Dilly",
//     "last_name": "Antonietti",
//     "email": "dantoniettic@lulu.com",
//     "gender": "Male",
//     "doj": "2023-03-23"
//   }, {
//     "first_name": "Ashley",
//     "last_name": "Wildblood",
//     "email": "awildbloodd@zimbio.com",
//     "gender": "Male",
//     "doj": "2023-09-16"
//   }, {
//     "first_name": "Pamelina",
//     "last_name": "Champ",
//     "email": "pchampe@reference.com",
//     "gender": "Female",
//     "doj": "2022-08-29"
//   }, {
//     "first_name": "Mildred",
//     "last_name": "McDowell",
//     "email": "mmcdowellf@epa.gov",
//     "gender": "Female",
//     "doj": "2024-03-27"
//   }, {
//     "first_name": "Sissie",
//     "last_name": "Gossipin",
//     "email": "sgossiping@wired.com",
//     "gender": "Female",
//     "doj": "2022-11-17"
//   }, {
//     "first_name": "Bertine",
//     "last_name": "Kilban",
//     "email": "bkilbanh@geocities.jp",
//     "gender": "Female",
//     "doj": "2023-02-27"
//   }, {
//     "first_name": "Karol",
//     "last_name": "Bazoge",
//     "email": "kbazogei@webs.com",
//     "gender": "Genderqueer",
//     "doj": "2020-03-19"
//   }, {
//     "first_name": "Alaster",
//     "last_name": "McCarry",
//     "email": "amccarryj@sphinn.com",
//     "gender": "Male",
//     "doj": "2020-05-11"
//   }, {
//     "first_name": "Rennie",
//     "last_name": "Endle",
//     "email": "rendlek@upenn.edu",
//     "gender": "Female",
//     "doj": "2023-07-30"
//   }, {
//     "first_name": "Darryl",
//     "last_name": "Lougheed",
//     "email": "dlougheedl@networkadvertising.org",
//     "gender": "Male",
//     "doj": "2024-02-29"
//   }, {
//     "first_name": "Lorine",
//     "last_name": "Mc Pake",
//     "email": "lmcpakem@delicious.com",
//     "gender": "Female",
//     "doj": "2023-02-11"
//   }, {
//     "first_name": "Lilah",
//     "last_name": "Bodega",
//     "email": "lbodegan@salon.com",
//     "gender": "Female",
//     "doj": "2024-01-15"
//   }, {
//     "first_name": "Farrell",
//     "last_name": "Shitliffe",
//     "email": "fshitliffeo@qq.com",
//     "gender": "Male",
//     "doj": "2024-08-22"
//   }, {
//     "first_name": "Geno",
//     "last_name": "Bagnell",
//     "email": "gbagnellp@parallels.com",
//     "gender": "Male",
//     "doj": "2019-11-05"
//   }, {
//     "first_name": "Isak",
//     "last_name": "Waltering",
//     "email": "iwalteringq@free.fr",
//     "gender": "Genderfluid",
//     "doj": "2021-09-07"
//   }, {
//     "first_name": "Sybilla",
//     "last_name": "Gaishson",
//     "email": "sgaishsonr@businesswire.com",
//     "gender": "Female",
//     "doj": "2020-04-26"
//   }, {
//     "first_name": "Carny",
//     "last_name": "Gritskov",
//     "email": "cgritskovs@huffingtonpost.com",
//     "gender": "Male",
//     "doj": "2023-07-14"
//   }, {
//     "first_name": "Ode",
//     "last_name": "Sayburn",
//     "email": "osayburnt@walmart.com",
//     "gender": "Male",
//     "doj": "2020-01-20"
//   }, {
//     "first_name": "Jamill",
//     "last_name": "Bridat",
//     "email": "jbridatu@washingtonpost.com",
//     "gender": "Male",
//     "doj": "2020-01-08"
//   }, {
//     "first_name": "Jeth",
//     "last_name": "Curtin",
//     "email": "jcurtinv@exblog.jp",
//     "gender": "Bigender",
//     "doj": "2021-06-14"
//   }, {
//     "first_name": "Von",
//     "last_name": "Mapson",
//     "email": "vmapsonw@google.de",
//     "gender": "Male",
//     "doj": "2022-05-20"
//   }, {
//     "first_name": "Shelton",
//     "last_name": "Augustin",
//     "email": "saugustinx@ning.com",
//     "gender": "Male",
//     "doj": "2022-10-31"
//   }, {
//     "first_name": "Lisha",
//     "last_name": "Digg",
//     "email": "ldiggy@parallels.com",
//     "gender": "Female",
//     "doj": "2024-01-24"
//   }, {
//     "first_name": "Bent",
//     "last_name": "Jeffryes",
//     "email": "bjeffryesz@princeton.edu",
//     "gender": "Male",
//     "doj": "2023-09-15"
//   }, {
//     "first_name": "Seward",
//     "last_name": "Wallentin",
//     "email": "swallentin10@amazon.co.jp",
//     "gender": "Male",
//     "doj": "2021-11-14"
//   }, {
//     "first_name": "Seamus",
//     "last_name": "Dunniom",
//     "email": "sdunniom11@opera.com",
//     "gender": "Male",
//     "doj": "2024-03-07"
//   }, {
//     "first_name": "Benji",
//     "last_name": "Lethbury",
//     "email": "blethbury12@domainmarket.com",
//     "gender": "Male",
//     "doj": "2022-06-20"
//   }, {
//     "first_name": "Marie",
//     "last_name": "Whelan",
//     "email": "mwhelan13@networkadvertising.org",
//     "gender": "Female",
//     "doj": "2020-09-01"
//   }, {
//     "first_name": "Gertrudis",
//     "last_name": "Newburn",
//     "email": "gnewburn14@sciencedaily.com",
//     "gender": "Female",
//     "doj": "2020-04-26"
//   }, {
//     "first_name": "Marina",
//     "last_name": "Huckstepp",
//     "email": "mhuckstepp15@cnn.com",
//     "gender": "Female",
//     "doj": "2024-05-24"
//   }, {
//     "first_name": "Rhett",
//     "last_name": "Truter",
//     "email": "rtruter16@archive.org",
//     "gender": "Male",
//     "doj": "2022-07-16"
//   }, {
//     "first_name": "Marji",
//     "last_name": "Kynge",
//     "email": "mkynge17@foxnews.com",
//     "gender": "Female",
//     "doj": "2020-08-24"
//   }, {
//     "first_name": "Nelia",
//     "last_name": "Yitzovitz",
//     "email": "nyitzovitz18@miibeian.gov.cn",
//     "gender": "Female",
//     "doj": "2022-05-23"
//   }, {
//     "first_name": "Zeke",
//     "last_name": "Longland",
//     "email": "zlongland19@google.com.hk",
//     "gender": "Male",
//     "doj": "2023-06-22"
//   }, {
//     "first_name": "Robinia",
//     "last_name": "Brambill",
//     "email": "rbrambill1a@about.com",
//     "gender": "Female",
//     "doj": "2019-12-08"
//   }, {
//     "first_name": "Karylin",
//     "last_name": "Newrick",
//     "email": "knewrick1b@abc.net.au",
//     "gender": "Female",
//     "doj": "2023-03-14"
//   }, {
//     "first_name": "Murray",
//     "last_name": "Patrone",
//     "email": "mpatrone1c@apache.org",
//     "gender": "Male",
//     "doj": "2022-04-04"
//   }, {
//     "first_name": "Eba",
//     "last_name": "Corner",
//     "email": "ecorner1d@narod.ru",
//     "gender": "Genderfluid",
//     "doj": "2024-04-18"
//   }, {
//     "first_name": "Dani",
//     "last_name": "Zellmer",
//     "email": "dzellmer1e@wired.com",
//     "gender": "Female",
//     "doj": "2024-02-21"
//   }, {
//     "first_name": "Tucker",
//     "last_name": "Sturch",
//     "email": "tsturch1f@newsvine.com",
//     "gender": "Male",
//     "doj": "2022-04-18"
//   }, {
//     "first_name": "Benetta",
//     "last_name": "Tilne",
//     "email": "btilne1g@com.com",
//     "gender": "Female",
//     "doj": "2022-09-26"
//   }, {
//     "first_name": "Lonna",
//     "last_name": "Steiner",
//     "email": "lsteiner1h@newsvine.com",
//     "gender": "Agender",
//     "doj": "2022-05-03"
//   }, {
//     "first_name": "Morena",
//     "last_name": "Ravenshear",
//     "email": "mravenshear1i@weibo.com",
//     "gender": "Polygender",
//     "doj": "2019-11-02"
//   }, {
//     "first_name": "Nollie",
//     "last_name": "Croshaw",
//     "email": "ncroshaw1j@mapquest.com",
//     "gender": "Male",
//     "doj": "2024-10-09"
//   }, {
//     "first_name": "Nollie",
//     "last_name": "Labarre",
//     "email": "nlabarre1k@salon.com",
//     "gender": "Female",
//     "doj": "2022-10-06"
//   }, {
//     "first_name": "Patrice",
//     "last_name": "Drewry",
//     "email": "pdrewry1l@independent.co.uk",
//     "gender": "Female",
//     "doj": "2022-04-12"
//   }, {
//     "first_name": "Ransell",
//     "last_name": "Dredge",
//     "email": "rdredge1m@springer.com",
//     "gender": "Male",
//     "doj": "2022-11-20"
//   }, {
//     "first_name": "Kissiah",
//     "last_name": "Lucio",
//     "email": "klucio1n@mac.com",
//     "gender": "Female",
//     "doj": "2021-09-21"
//   }, {
//     "first_name": "Emile",
//     "last_name": "Cosyns",
//     "email": "ecosyns1o@blogspot.com",
//     "gender": "Male",
//     "doj": "2023-07-06"
//   }, {
//     "first_name": "Fidelity",
//     "last_name": "Attwoul",
//     "email": "fattwoul1p@washington.edu",
//     "gender": "Female",
//     "doj": "2020-11-29"
//   }, {
//     "first_name": "Lu",
//     "last_name": "Tow",
//     "email": "ltow1q@pbs.org",
//     "gender": "Female",
//     "doj": "2023-04-13"
//   }, {
//     "first_name": "Barrett",
//     "last_name": "Ragbourne",
//     "email": "bragbourne1r@dailymail.co.uk",
//     "gender": "Male",
//     "doj": "2023-11-18"
//   }, {
//     "first_name": "Ave",
//     "last_name": "Strode",
//     "email": "astrode1s@yahoo.com",
//     "gender": "Male",
//     "doj": "2020-03-21"
//   }, {
//     "first_name": "Pauly",
//     "last_name": "de Nore",
//     "email": "pdenore1t@nyu.edu",
//     "gender": "Male",
//     "doj": "2020-05-27"
//   }, {
//     "first_name": "Brandi",
//     "last_name": "Fell",
//     "email": "bfell1u@wix.com",
//     "gender": "Genderqueer",
//     "doj": "2022-01-12"
//   }, {
//     "first_name": "Aland",
//     "last_name": "Dring",
//     "email": "adring1v@yelp.com",
//     "gender": "Genderfluid",
//     "doj": "2022-12-09"
//   }, {
//     "first_name": "Rab",
//     "last_name": "Gori",
//     "email": "rgori1w@harvard.edu",
//     "gender": "Male",
//     "doj": "2023-02-05"
//   }, {
//     "first_name": "Lay",
//     "last_name": "Antill",
//     "email": "lantill1x@time.com",
//     "gender": "Male",
//     "doj": "2023-05-16"
//   }, {
//     "first_name": "Hurleigh",
//     "last_name": "Priver",
//     "email": "hpriver1y@t-online.de",
//     "gender": "Male",
//     "doj": "2021-12-10"
//   }, {
//     "first_name": "Bale",
//     "last_name": "Dumphy",
//     "email": "bdumphy1z@indiatimes.com",
//     "gender": "Male",
//     "doj": "2019-11-07"
//   }, {
//     "first_name": "Beth",
//     "last_name": "Oulett",
//     "email": "boulett20@flickr.com",
//     "gender": "Female",
//     "doj": "2020-03-20"
//   }, {
//     "first_name": "Artemus",
//     "last_name": "Greguoli",
//     "email": "agreguoli21@biglobe.ne.jp",
//     "gender": "Male",
//     "doj": "2023-08-17"
//   }, {
//     "first_name": "Kym",
//     "last_name": "Nancekivell",
//     "email": "knancekivell22@comsenz.com",
//     "gender": "Female",
//     "doj": "2020-09-30"
//   }, {
//     "first_name": "Payton",
//     "last_name": "Manvell",
//     "email": "pmanvell23@vinaora.com",
//     "gender": "Male",
//     "doj": "2023-06-08"
//   }, {
//     "first_name": "Uriel",
//     "last_name": "Udall",
//     "email": "uudall24@ow.ly",
//     "gender": "Male",
//     "doj": "2023-11-25"
//   }, {
//     "first_name": "Caye",
//     "last_name": "Fant",
//     "email": "cfant25@rakuten.co.jp",
//     "gender": "Female",
//     "doj": "2020-04-29"
//   }, {
//     "first_name": "Shaw",
//     "last_name": "Klamp",
//     "email": "sklamp26@ihg.com",
//     "gender": "Male",
//     "doj": "2023-06-27"
//   }, {
//     "first_name": "Wilhelm",
//     "last_name": "Dunklee",
//     "email": "wdunklee27@so-net.ne.jp",
//     "gender": "Male",
//     "doj": "2022-06-08"
//   }, {
//     "first_name": "Dominique",
//     "last_name": "Haensel",
//     "email": "dhaensel28@weibo.com",
//     "gender": "Male",
//     "doj": "2023-12-09"
//   }, {
//     "first_name": "Humphrey",
//     "last_name": "Turfus",
//     "email": "hturfus29@google.cn",
//     "gender": "Male",
//     "doj": "2022-03-16"
//   }, {
//     "first_name": "Maure",
//     "last_name": "Dalgarnowch",
//     "email": "mdalgarnowch2a@prlog.org",
//     "gender": "Female",
//     "doj": "2021-05-08"
//   }, {
//     "first_name": "Jilleen",
//     "last_name": "Trelease",
//     "email": "jtrelease2b@mapquest.com",
//     "gender": "Female",
//     "doj": "2024-02-02"
//   }, {
//     "first_name": "Angie",
//     "last_name": "Fibbings",
//     "email": "afibbings2c@engadget.com",
//     "gender": "Female",
//     "doj": "2022-07-11"
//   }, {
//     "first_name": "Kathy",
//     "last_name": "Pallis",
//     "email": "kpallis2d@yale.edu",
//     "gender": "Female",
//     "doj": "2024-08-13"
//   }, {
//     "first_name": "Adeline",
//     "last_name": "Glencorse",
//     "email": "aglencorse2e@hp.com",
//     "gender": "Female",
//     "doj": "2021-06-09"
//   }, {
//     "first_name": "Karlene",
//     "last_name": "Bartlomiej",
//     "email": "kbartlomiej2f@globo.com",
//     "gender": "Female",
//     "doj": "2020-09-03"
//   }, {
//     "first_name": "Ingrim",
//     "last_name": "Balstone",
//     "email": "ibalstone2g@noaa.gov",
//     "gender": "Male",
//     "doj": "2021-07-21"
//   }, {
//     "first_name": "Rosie",
//     "last_name": "Brassington",
//     "email": "rbrassington2h@bing.com",
//     "gender": "Female",
//     "doj": "2022-09-06"
//   }, {
//     "first_name": "Lauralee",
//     "last_name": "Corselles",
//     "email": "lcorselles2i@ftc.gov",
//     "gender": "Female",
//     "doj": "2020-06-11"
//   }, {
//     "first_name": "Rudyard",
//     "last_name": "Tainton",
//     "email": "rtainton2j@latimes.com",
//     "gender": "Male",
//     "doj": "2023-03-15"
//   }, {
//     "first_name": "Rania",
//     "last_name": "Preuvost",
//     "email": "rpreuvost2k@usda.gov",
//     "gender": "Female",
//     "doj": "2022-02-26"
//   }, {
//     "first_name": "Willy",
//     "last_name": "Twycross",
//     "email": "wtwycross2l@artisteer.com",
//     "gender": "Male",
//     "doj": "2020-08-07"
//   }, {
//     "first_name": "Paula",
//     "last_name": "Ludl",
//     "email": "pludl2m@live.com",
//     "gender": "Female",
//     "doj": "2021-02-18"
//   }, {
//     "first_name": "Feliks",
//     "last_name": "Ducker",
//     "email": "fducker2n@ocn.ne.jp",
//     "gender": "Male",
//     "doj": "2020-01-06"
//   }, {
//     "first_name": "Cordy",
//     "last_name": "Ralston",
//     "email": "cralston2o@slashdot.org",
//     "gender": "Male",
//     "doj": "2021-04-17"
//   }, {
//     "first_name": "Terese",
//     "last_name": "Adanez",
//     "email": "tadanez2p@mozilla.org",
//     "gender": "Female",
//     "doj": "2024-04-04"
//   }, {
//     "first_name": "Jess",
//     "last_name": "Bosch",
//     "email": "jbosch2q@pinterest.com",
//     "gender": "Male",
//     "doj": "2021-07-29"
//   }, {
//     "first_name": "Leshia",
//     "last_name": "Rennison",
//     "email": "lrennison2r@ning.com",
//     "gender": "Female",
//     "doj": "2021-07-14"
//   }]
//   )
  
// db.emoployee.find()

// db.emoployee.find({ "first_name": "Genevieve" })

// db.emoployee.find({ doj: { $gt: "2023-01-01" } })

// db.emoployee.find()

// db.inventory.insertMany([
//     { item: "journal", qty: 25, tags: ["blank", "red"], dim_cm: [ 14, 21 ] },
//     { item: "notebook", qty: 50, tags: ["red", "blank"], dim_cm: [ 14, 21 ] },
//     { item: "paper", qty: 100, tags: ["red", "blank", "plain"], dim_cm: [ 14, 21 ] },
//     { item: "planner", qty: 75, tags: ["blank", "red"], dim_cm: [ 22.85, 30 ] },
//     { item: "postcard", qty: 45, tags: ["blue"], dim_cm: [ 10, 15.25 ] }
//  ]);

//  db.inventory.find()

db.inventory.find( { tags: ["red", "blank"] } )
