version: '3'

services:

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend/frontapp
    ports:
      - "80:80"

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"